---
- name: Install rust
  become: yes
  dnf:
    name: [
      "cargo",
      "rust",
      "rust-analyzer",
      "rust-src",
      "rustfmt",
    ]
    state: present
  when: install_rust
  tags:
    - install_rust
