---
- name: Remove unneeded packages
  become: yes
  dnf:
    name: "{{ packages_to_remove | default([]) }}"
    state: absent
    autoremove: yes
    allowerasing: yes
  tags:
    - remove_unneeded_packages
